id: P004570
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN1619
  title: སྣར་ཐང་བརྒྱ་རྩ་ལས་འབྱུང་བའི་ཡི་དམ་ལྷ་ཚོགས་རྣམས་ཀྱི་སྒྲུབ་ཐབས་རྗེས་གནང་དང་བཅས་པའི་ཡི་གེ།
  author: ''
  volumes:
    0a473aec09454701b19fa8fe109805aa:
      image_group_id: I3CN1621
      title: ''
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
