id: opecha:P004570
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN1619
  title: སྣར་ཐང་བརྒྱ་རྩ་ལས་འབྱུང་བའི་ཡི་དམ་ལྷ་ཚོགས་རྣམས་ཀྱི་སྒྲུབ་ཐབས་རྗེས་གནང་དང་བཅས་པའི་ཡི་གེ།
  volume: ''
  author: ''
