id: I2F81FFD0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T21:32:04+00:00'
last_modified: '2022-06-08T02:00:44.789132+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN1619
  title: སྣར་ཐང་བརྒྱ་རྩ་ལས་འབྱུང་བའི་ཡི་དམ་ལྷ་ཚོགས་རྣམས་ཀྱི་སྒྲུབ་ཐབས་རྗེས་གནང་དང་བཅས་པའི་ཡི་གེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BABB:
      image_group_id: I3CN1621
      title: ''
      total_pages: 90
      order: 1
      base_file: BABB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
